markdown: rdiscount
rdiscount:
    extensions: [smart]
pygments: false
#server_port: 80

# https://github.com/mojombo/jekyll/issues/156
# permalink: /:categories/:title/
permalink: /:title/
post_dirs: true

#exclude: deploy.sh, config.rb, */style.scss
#include: .htaccess WTF: https://github.com/mojombo/jekyll/issues/363